// <auto-generated />
using System;
using FoodSafety.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodSafety.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200408035749_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("FoodSafety.API.Models.Inspection", b =>
                {
                    b.Property<string>("InspectionSerialNum")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InspectionBusinessName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("InspectionClosedBusiness")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InspectionResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InspectionScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InspectionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RestuarantBusinessID")
                        .HasColumnType("TEXT");

                    b.HasKey("InspectionSerialNum");

                    b.HasIndex("RestuarantBusinessID");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("FoodSafety.API.Models.Restuarant", b =>
                {
                    b.Property<string>("BusinessID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Desciption")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longtitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZipCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusinessID");

                    b.ToTable("Restuarants");
                });

            modelBuilder.Entity("FoodSafety.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodSafety.API.Models.Violation", b =>
                {
                    b.Property<string>("ViolationRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionSerialNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectionSerialNum1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViolationDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("ViolationPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViolationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ViolationRecordId");

                    b.HasIndex("InspectionSerialNum1");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("FoodSafety.API.Models.Inspection", b =>
                {
                    b.HasOne("FoodSafety.API.Models.Restuarant", "Restuarant")
                        .WithMany("Inspections")
                        .HasForeignKey("RestuarantBusinessID");
                });

            modelBuilder.Entity("FoodSafety.API.Models.Violation", b =>
                {
                    b.HasOne("FoodSafety.API.Models.Inspection", "Inspection")
                        .WithMany("Violations")
                        .HasForeignKey("InspectionSerialNum1");
                });
#pragma warning restore 612, 618
        }
    }
}
